version: '3'

services:
    node:
        build: .
        links:
            - redis
        ports:
            - "8080:8080"
        volumes:
            - ./:/src
        env_file: ~/status-check.env

    redis:
        image: redis
        ports:
            - "6379"
